name: Docker Latest

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "playit-latest/**"
  pull_request:
    branches:
      - main
    paths:
      - "playit-latest/**"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/payit"
      context: "playit-latest"
      dockerfile: "playit-latest/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Simple plyit.gg docker"
      docker_label_description: "playit.gg docker"
      version_detecter: true
      version_detecter_file: "playit-latest/Dockerfile"
      version_detecter_var: "PLAYIT_VERSION="
